version: "2"

networks:
  ruslan-workshop-shared:

services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ruslan-workshop-shared
    depends_on:
      - ruslan-app
      - market-api


  ruslan-app:
    image: ruslan-app:latest
    container_name: ruslan-app
    build:
      context: ./web/ruslan-app
      dockerfile: ./Dockerfile
    expose:
      - 80
    networks:
      - ruslan-workshop-shared

  market-db:
    image: postgres:latest
    expose:
      - 5432
    restart: always
    volumes:
      - ./services/MarketService/dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - market-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "ya"
      POSTGRES_PASSWORD: "yeet"
      POSTGRES_DB: "market-db"
    networks:
      - ruslan-workshop-shared

  market-api:
    image: market-api:latest
    container_name: market-api
    build:
      context: ./services/MarketService
      dockerfile: ./Dockerfile
    expose:
      - 80
    environment:
      DB_CONNECTION_STRING: "host=market-db;port=5432;database=market-db;username=ya;password=yeet"
    depends_on:
      - market-db
    networks:
      - ruslan-workshop-shared



volumes:
  market-db-volume:
