version: "3"

networks:
  ruslan-workshop-shared:

services: 
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf.local:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ruslan-workshop-shared
    depends_on:
      - ruslan-app
{depends_on_list}

  ruslan-app:
    image: ruslan-app:latest
    container_name: ruslan-app
    build:
      context: ../web/ruslan-app
      dockerfile: ./Dockerfile
    expose:
      - 80
    networks:
      - ruslan-workshop-shared

{services}

volumes:
{volume_list}